version: "3"

services:
 zookeeper:
  image: debezium/zookeeper:0.9
  container_name: zookeeper
  ports:
    - 2181:2181 
    - 2888:2888 
    - 3888:3888

 kafka:
  image: debezium/kafka:0.9
  container_name: kafka
  depends_on:
   - zookeeper
  ports:
   - "9092:9092"
  environment:
   ZOOKEEPER_CONNECT: zookeeper:2181
   LISTENERS: PLAINTEXT://kafka:9092
   ADVERTISED.LISTENERS: PLAINTEXT://kafka:9092
  links:
    - zookeeper:zookeeper
   
 db:
  image: couchbase
  container_name: db
  ports:
   - 8091-8096:8091-8096
   - 11210-11211:11210-11211
   
 connect:
  image: couchbasedebezium
  container_name: connect
  ports:
   - 8083:8083
  depends_on:
   - zookeeper
   - kafka
   - db
  environment:
   GROUP_ID: 1
   CONFIG_STORAGE_TOPIC: my_connect_configs
   OFFSET_STORAGE_TOPIC: my_connect_offsets 
   STATUS_STORAGE_TOPIC: my_connect_statuses
   BOOTSTRAP_SERVERS: kafka:9092
  links:
   - kafka:kafka
   - zookeeper:zookeper
   - db:db
   
  